# Generated by Django 4.2.6 on 2023-10-31 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFazenda', models.CharField(max_length=50)),
                ('altitude', models.IntegerField()),
                ('areaTotal', models.IntegerField()),
                ('nomeRodoviaKm', models.CharField(max_length=70)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='TexturaSolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSolo', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeUsuario', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Talhoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_talhoes', models.IntegerField()),
                ('nomeFazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='Exportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exportadora', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='AreaPlantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_plantio', models.IntegerField()),
                ('nomeFazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='AnaliseSolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField()),
                ('materia_organica_porcentagem', models.IntegerField()),
                ('condutividade_eletrica', models.FloatField()),
                ('textura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.texturasolo')),
            ],
        ),
    ]
