# Generated by Django 4.2.6 on 2023-10-31 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_texturasolo_tiposolo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
    ]
