# Generated by Django 4.2.6 on 2023-10-31 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cidade_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisesolo',
            options={'verbose_name': 'Analise Solo', 'verbose_name_plural': 'Analise Solos'},
        ),
        migrations.AlterModelOptions(
            name='areaplantio',
            options={'verbose_name': 'Area Plantio', 'verbose_name_plural': 'Areas Plantio'},
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='exportadora',
            options={'verbose_name': 'Exportadora', 'verbose_name_plural': 'Exportadoras'},
        ),
        migrations.AlterModelOptions(
            name='fazenda',
            options={'verbose_name': 'Fazenda', 'verbose_name_plural': 'Fazendas'},
        ),
        migrations.AlterModelOptions(
            name='talhoes',
            options={'verbose_name': 'Talhao', 'verbose_name_plural': 'Talhoes'},
        ),
        migrations.AlterModelOptions(
            name='texturasolo',
            options={'verbose_name': 'Textura Solo', 'verbose_name_plural': 'Texturas Solo'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
