# Generated by Django 4.2.6 on 2023-10-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_analisesolo_options_alter_areaplantio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texturasolo',
            name='tipoSolo',
            field=models.CharField(max_length=50),
        ),
    ]
