# Generated by Django 4.2.6 on 2023-11-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_texturasolo_tiposolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisesolo',
            name='qtde_Calcio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analisesolo',
            name='qtde_Magnesio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analisesolo',
            name='qtde_Potassio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
