# Generated by Django 4.2.6 on 2023-11-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_analisesolo_qtde_calcio_analisesolo_qtde_magnesio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisesolo',
            name='condutividade_eletrica',
        ),
    ]
