# Generated by Django 4.2.6 on 2023-11-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_analisesolo_condutividade_eletrica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='nomeCidade',
            new_name='nome_cidade',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nomeUsuario',
            new_name='nome_usuario',
        ),
    ]
